Upgrade to Ember-CLI 2.8.0
alsemyonov/ember-faye pull request #4
Opened 2017-04-26 19:14 UTC by cyril-sf

2017-04-28 06:50 UTC, alsemyonov requested changes

2017-04-28 06:50 UTC, alsemyonov commented on .travis.yml
> +  - node_modules/phantomjs-prebuilt/bin/phantomjs --version
@cyril-sf, could you fix this to make Travis CI pass? 
Right now it reports: [`node_modules/phantomjs-prebuilt/bin/phantomjs: No such file or directory
`](https://travis-ci.org/alsemyonov/ember-faye/jobs/226135674#L297)

2017-05-01 15:33 UTC, cyril-sf commented
@alsemyonov Problem fixed!

2017-05-01 19:20 UTC, alsemyonov approved these changes

2017-05-01 19:22 UTC, merged